import { getLocale, setLocale, t } from './i18n.js';
import { renderCatalog } from './catalog/catalog-view.js';
import { loadProduct } from './catalog/catalog-data.js';
import { renderAuth } from './auth/auth-view.js';
import { authApi } from './auth/auth-api.js';
import { checkoutApi } from './checkout/checkout-api.js';
import { renderLibrary, renderWatch } from './library/library-view.js';
import { renderSellerDashboard } from './seller/seller-dashboard.js';
import { renderSellerProducts } from './seller/seller-products.js';
import { renderSellerUpload } from './seller/seller-upload.js';
import { renderSellerEarnings } from './seller/seller-earnings.js';
import { renderSellerPayouts } from './seller/seller-payouts.js';
import { renderSellerProfile } from './seller/seller-profile.js';
import { renderSellerApplication } from './seller/seller-application-view.js';
import { renderCreators } from './creators/creators-view.js';
import { renderAdminDashboard } from './admin/admin-dashboard.js';
import { renderAdminPayouts } from './admin/admin-payouts.js';
import { renderAdminVerifications } from './admin/admin-verifications.js';
import { renderSellerApplications } from './admin/seller-applications.js';

const app = document.querySelector('#app');
function header(locale) { return `<header class="site-header"><a class="brand" href="#/">VIDEO MARKET</a><nav aria-label="Primary"><a href="#/browse">${t('nav.discover')}</a><a href="#/categories">${t('nav.categories')}</a><a href="#/popular">${t('nav.popular')}</a><a href="#/library">My Library</a><a href="#/creators">${t('nav.creators')}</a></nav><div class="header-actions"><select id="locale" aria-label="Language"><option value="en" ${locale === 'en' ? 'selected' : ''}>EN</option><option value="ja" ${locale === 'ja' ? 'selected' : ''}>日本語</option><option value="es" ${locale === 'es' ? 'selected' : ''}>ES</option><option value="pt-BR" ${locale === 'pt-BR' ? 'selected' : ''}>PT</option><option value="fr" ${locale === 'fr' ? 'selected' : ''}>FR</option><option value="de" ${locale === 'de' ? 'selected' : ''}>DE</option><option value="it" ${locale === 'it' ? 'selected' : ''}>IT</option><option value="ko" ${locale === 'ko' ? 'selected' : ''}>한국어</option><option value="zh-CN" ${locale === 'zh-CN' ? 'selected' : ''}>简体中文</option><option value="zh-TW" ${locale === 'zh-TW' ? 'selected' : ''}>繁體中文</option></select><a href="#/login">${t('nav.login')}</a><a class="button" href="#/register">${t('nav.signup')}</a></div></header>`; }
function wireLocale() { document.querySelector('#locale')?.addEventListener('change', (event) => { setLocale(event.target.value); render(); }); }
function renderHome() { const locale = getLocale(); app.innerHTML = `${header(locale)}<main><section class="hero"><p class="eyebrow">${t('hero.eyebrow')}</p><h1>${t('hero.title')}</h1><p>${t('hero.description')}</p><div class="hero-actions"><a class="button" href="#/browse">${t('hero.explore')}</a><a class="button secondary" href="#/seller/register">${t('hero.creator')}</a></div></section><section class="trust-grid"><div><strong>For buyers</strong><span>Discover, purchase and access your library.</span></div><div><strong>For creators</strong><span>Publish, sell and track earnings.</span></div><div><strong>For operators</strong><span>Moderate and manage the marketplace.</span></div></section></main>`; wireLocale(); }
async function startCheckout(productId) { const message = document.querySelector('#checkout-message'); const button = document.querySelector('#checkout'); button.disabled = true; message.textContent = 'Preparing secure checkout…'; try { await authApi.me(); } catch (error) { if (error.status === 401) { location.hash = `#/login?return=/product/${encodeURIComponent(productId)}`; return; } message.textContent = 'Unable to verify your session.'; button.disabled = false; return; } try { const intent = await checkoutApi.purchaseIntent(productId, getLocale()); const order = await checkoutApi.createOrder(productId); const session = await checkoutApi.checkout(order.order.id); if (session?.session?.url) { window.location.assign(session.session.url); return; } message.textContent = session?.session?.status === 'not_configured' ? 'Checkout provider is not configured yet. No payment was charged.' : `Checkout ready (${intent.data.currency} ${intent.data.price}), but no redirect URL was returned.`; button.disabled = false; } catch (error) { message.textContent = error.body?.error?.message || 'Unable to start checkout.'; button.disabled = false; } }
async function renderProduct(id) { const locale = getLocale(); app.innerHTML = `${header(locale)}<main class="product-detail-page"><div id="product-detail-root"><section class="empty-state"><p>Loading…</p></section></div></main>`; wireLocale(); const root = document.querySelector('#product-detail-root'); try { const payload = await loadProduct(id, { locale, allowFallback: false }); const product = payload.data || null; if (!product) { root.innerHTML = `<section class="empty-state"><h1>Product not found</h1><a class="button" href="#/browse">Back to catalog</a></section>`; return; } const currency = product.price_currency || product.currency || 'USD'; const price = Number(product.price_amount ?? product.price ?? 0); root.innerHTML = `<a class="back-link" href="#/browse">← ${t('nav.discover')}</a><section class="product-detail"><div class="product-detail-media"><div class="product-thumb large">VIDEO</div></div><div class="product-detail-copy"><p class="eyebrow">${product.category || ''}</p><h1>${product.title || ''}</h1><p class="seller-line">${product.seller || ''}</p><p class="detail-description">${product.description || 'Premium video product. Streaming and download availability are controlled by the product and operator policy.'}</p><div class="detail-purchase"><strong>${new Intl.NumberFormat(locale, { style: 'currency', currency }).format(price)}</strong><button class="button" type="button" id="checkout">Purchase</button></div><p id="checkout-message" class="microcopy" aria-live="polite">Secure checkout is ready.</p></div></section>`; document.querySelector('#checkout')?.addEventListener('click', () => startCheckout(id)); } catch (error) { root.innerHTML = `<section class="error-state"><h1>Product unavailable</h1><p>Please return to the catalog and try again.</p><a class="button" href="#/browse">Back to catalog</a></section>`; } }
async function renderBrowse() { const locale = getLocale(); const params = new URLSearchParams(location.hash.split('?')[1] || ''); const query = params.get('q') || ''; const category = params.get('category') || ''; app.innerHTML = header(locale) + '<main id="catalog-root"></main>'; wireLocale(); await renderCatalog({ root: document.querySelector('#catalog-root'), locale, t, query, category, onNavigate: (path) => { location.hash = `#${path}`; } }); }
function renderAuthPage(mode) { app.innerHTML = header(getLocale()) + '<div id="auth-root"></div>'; wireLocale(); renderAuth(document.querySelector('#auth-root'), mode); }
async function renderLibraryPage() { app.innerHTML = header(getLocale()) + '<main id="library-root"></main>'; wireLocale(); await renderLibrary(document.querySelector('#library-root')); }
async function renderWatchPage(productId) { app.innerHTML = header(getLocale()) + '<main id="watch-root"></main>'; wireLocale(); try { await authApi.me(); renderWatch(document.querySelector('#watch-root'), productId); } catch (error) { if (error.status === 401) { location.hash = `#/login?return=/watch/${encodeURIComponent(productId)}`; return; } document.querySelector('#watch-root').innerHTML = '<section class="empty-state"><h2>Player unavailable</h2><p>Please try again shortly.</p></section>'; } }
async function renderSellerPage(section = 'overview') { app.innerHTML = header(getLocale()) + '<main id="seller-root"></main>'; wireLocale(); const root = document.querySelector('#seller-root'); try { await authApi.me(); if (section === 'register') return renderSellerApplication(root); if (section === 'products') return renderSellerProducts(root); if (section === 'upload') return renderSellerUpload(root); if (section === 'sales') return renderSellerEarnings(root); if (section === 'payouts') return renderSellerPayouts(root); if (section === 'profile' || section === 'verification') return renderSellerProfile(root); root.innerHTML = renderSellerDashboard(); } catch (error) { if (section === 'register' && error.status === 401) return renderSellerApplication(root); if (error.status === 401) { location.hash = `#/login?return=/seller/${encodeURIComponent(section)}`; return; } root.innerHTML = '<section class="empty-state"><h2>Seller dashboard unavailable</h2><p>Please try again shortly.</p></section>'; } }
async function renderAdminPage(section) { app.innerHTML = header(getLocale()) + '<main id="admin-root"></main>'; wireLocale(); const root = document.querySelector('#admin-root'); try { await authApi.me(); if (!section || section === 'overview') return root.innerHTML = renderAdminDashboard(); if (section === 'payouts') return renderAdminPayouts(root); if (section === 'seller-applications') return renderSellerApplications(root); if (section === 'verification' || section === 'verifications' || section === 'seller-verifications') return renderAdminVerifications(root); root.innerHTML = renderAdminDashboard(); } catch (error) { if (error.status === 401 || error.status === 403) { root.innerHTML = '<section class="empty-state"><h2>Admin access required</h2><p>Your account does not have permission to view this area.</p></section>'; return; } root.innerHTML = '<section class="empty-state"><h2>Admin dashboard unavailable</h2><p>Please try again shortly.</p></section>'; } }
async function renderCreatorsPage() { app.innerHTML = header(getLocale()) + '<main id="creators-root"></main>'; wireLocale(); renderCreators(document.querySelector('#creators-root')); }
function render() { const rawPath = location.hash.replace(/^#/, '').split('?')[0] || '/'; const productMatch = rawPath.match(/^\/product\/([^/]+)$/); const watchMatch = rawPath.match(/^\/watch\/([^/]+)$/); const sellerMatch = rawPath.match(/^\/seller(?:\/([^/]+))?$/); const adminMatch = rawPath.match(/^\/admin(?:\/([^/]+))?$/); if (productMatch) return renderProduct(decodeURIComponent(productMatch[1])); if (watchMatch) return renderWatchPage(decodeURIComponent(watchMatch[1])); if (sellerMatch) return renderSellerPage(sellerMatch[1] || 'overview'); if (adminMatch) return renderAdminPage(adminMatch[1]); if (rawPath === '/creators') return renderCreatorsPage(); if (rawPath === '/browse' || rawPath === '/categories' || rawPath === '/popular') return renderBrowse(); if (rawPath === '/library') return renderLibraryPage(); if (rawPath === '/login') return renderAuthPage('login'); if (rawPath === '/register') return renderAuthPage('register'); renderHome(); }
window.addEventListener('hashchange', render); render();