import { getLocale, setLocale, t } from './i18n.js';
import { renderCatalog } from './catalog/catalog-view.js';
import { fetchProductDetail } from './catalog/product-detail-api.js';
import { renderAuth } from './auth/auth-view.js';
import { authApi } from './auth/auth-api.js';
import { checkoutApi } from './checkout/checkout-api.js';
import { renderLibrary, renderWatch } from './library/library-view.js';
import { renderSellerDashboard } from './seller/seller-dashboard.js';
import { renderSellerProducts } from './seller/seller-products.js';
import { renderSellerUpload } from './seller/seller-upload.js';
import { renderSellerEarnings } from './seller/seller-earnings.js';
import { renderSellerPayouts } from './seller/seller-payouts.js';
import { renderSellerProfile } from './seller/seller-profile.js';
import { renderSellerApplication } from './seller/seller-application-view.js';
import { renderCreators } from './creators/creators-view.js';
import { renderAdminDashboard } from './admin/admin-dashboard.js';
import { renderAdminPayouts } from './admin/admin-payouts.js';
import { renderAdminVerifications } from './admin/admin-verifications.js';
import { renderSellerApplications } from './admin/seller-applications.js';

const app = document.querySelector('#app');
function header(locale) { return `<header class="site-header"><a class="brand" href="#/">VIDORA</a><nav aria-label="Primary"><a href="#/browse">${t('nav.discover')}</a><a href="#/categories">${t('nav.categories')}</a><a href="#/popular">${t('nav.popular')}</a><a href="#/library">My Library</a><a href="#/creators">${t('nav.creators')}</a></nav><div class="header-actions"><select id="locale" aria-label="Language"><option value="en" ${locale === 'en' ? 'selected' : ''}>EN</option><option value="ja" ${locale === 'ja' ? 'selected' : ''}>日本語</option><option value="es" ${locale === 'es' ? 'selected' : ''}>ES</option><option value="pt-BR" ${locale === 'pt-BR' ? 'selected' : ''}>PT</option><option value="fr" ${locale === 'fr' ? 'selected' : ''}>FR</option><option value="de" ${locale === 'de' ? 'selected' : ''}>DE</option><option value="it" ${locale === 'it' ? 'selected' : ''}>IT</option><option value="ko" ${locale === 'ko' ? 'selected' : ''}>한국어</option><option value="zh-CN" ${locale === 'zh-CN' ? 'selected' : ''}>简体中文</option><option value="zh-TW" ${locale === 'zh-TW' ? 'selected' : ''}>繁體中文</option></select><a href="#/login">${t('nav.login')}</a><a class="button" href="#/register">${t('nav.signup')}</a></div></header>`; }
function wireLocale() { document.querySelector('#locale')?.addEventListener('change', (event) => { setLocale(event.target.value); render(); }); }
async function renderHome() { const locale = getLocale(); app.innerHTML = `${header(locale)}<main class="home"><section class="hero hero-home"><div class="hero-copy"><p class="eyebrow">${t('hero.eyebrow')}</p><h1>${t('hero.title')}</h1><p>${t('hero.description')}</p><div class="hero-search"><input id="home-search" placeholder="Search videos, creators or categories" aria-label="Search videos"><button class="button" id="home-search-button">${t('hero.explore')} →</button></div><div class="hero-actions"><a class="button secondary" href="#/seller/register">${t('hero.creator')}</a><span class="hero-note">Secure checkout · Private library · Protected downloads</span></div></div><div class="hero-art"><div class="art-window"><div class="art-top"><i></i><i></i><i></i></div><div class="art-scene"><div class="play">▶</div><span>VIDORA</span><small>Premium video marketplace</small></div></div><div class="floating-card floating-one"><strong>4.9 ★</strong><span>Creator rating</span></div><div class="floating-card floating-two"><strong>Private</strong><span>Buyer access</span></div></div></section><section class="benefits"><div><span class="benefit-icon">01</span><strong>Discover</strong><p>Search and compare videos in one place.</p></div><div><span class="benefit-icon">02</span><strong>Buy with confidence</strong><p>Clear product details and a protected checkout flow.</p></div><div><span class="benefit-icon">03</span><strong>Watch anywhere</strong><p>Your purchases stay in your private library.</p></div><div><span class="benefit-icon">04</span><strong>Download</strong><p>Eligible purchases include protected downloads.</p></div></section><section class="home-section"><div class="section-heading"><div><p class="eyebrow">Start exploring</p><h2>Find your next video</h2></div><a href="#/browse">View all →</a></div><div id="home-catalog"></div></section><section class="creator-banner"><div><p class="eyebrow">For creators</p><h2>Turn your videos into a business.</h2><p>Publish products, manage your catalog, track earnings and request payouts from one creator workspace.</p></div><a class="button" href="#/seller/register">Start selling →</a></section><footer class="site-footer"><div><strong>VIDORA</strong><span>Discover. Buy. Sell.</span></div><div><a href="#/browse">Discover</a><a href="#/creators">Creators</a><a href="#/seller/register">Sell videos</a></div></footer></main>`; wireLocale(); const search = document.querySelector('#home-search'); const go = () => { const value = search.value.trim(); location.hash = `#/browse${value ? `?q=${encodeURIComponent(value)}` : ''}`; }; document.querySelector('#home-search-button')?.addEventListener('click', go); search?.addEventListener('keydown', (event) => { if (event.key === 'Enter') go(); }); await renderCatalog({ root: document.querySelector('#home-catalog'), locale, t, onNavigate: (path) => { location.hash = `#${path}`; } }); }
async function startCheckout(productId) { const message = document.querySelector('#checkout-message'); const button = document.querySelector('#checkout'); button.disabled = true; message.textContent = 'Preparing secure checkout…'; try { await authApi.me(); } catch (error) { if (error.status === 401) { location.hash = `#/login?return=/product/${encodeURIComponent(productId)}`; return; } message.textContent = 'Unable to verify your session.'; button.disabled = false; return; } try { const intent = await checkoutApi.purchaseIntent(productId, getLocale()); const order = await checkoutApi.createOrder(productId); const session = await checkoutApi.checkout(order.order.id); if (session?.session?.url) { window.location.assign(session.session.url); return; } message.textContent = session?.session?.status === 'not_configured' ? 'Checkout provider is not configured yet. No payment was charged.' : `Checkout ready (${intent.data.currency} ${intent.data.price}), but no redirect URL was returned.`; button.disabled = false; } catch (error) { message.textContent = error.body?.error?.message || 'Unable to start checkout.'; button.disabled = false; } }
async function renderProduct(id) { const locale = getLocale(); app.innerHTML = `${header(locale)}<main class="product-detail-page"><section class="product-detail"><div class="product-detail-media"><div class="product-thumb large"><span>▶</span></div></div><div class="product-detail-copy"><p id="product-category" class="eyebrow">Loading…</p><h1 id="product-title">Loading product…</h1><p id="product-seller" class="seller-line"></p><p id="product-description" class="detail-description"></p><div class="detail-purchase"><strong id="product-price"></strong><button class="button" type="button" id="checkout" disabled>Purchase</button></div><p id="checkout-message" class="microcopy" aria-live="polite">Loading product…</p></div></section></main>`; wireLocale(); try { const product = await fetchProductDetail(id, { locale }); if (!product) throw new Error('PRODUCT_NOT_FOUND'); document.querySelector('#product-category').textContent = product.category || ''; document.querySelector('#product-title').textContent = product.title || ''; document.querySelector('#product-seller').textContent = product.seller || ''; document.querySelector('#product-description').textContent = product.description || 'Premium video product. Streaming and download availability are controlled by the product and operator policy.'; const amount = Number(product.price_amount ?? product.price ?? 0); const currency = product.price_currency || product.currency || 'USD'; document.querySelector('#product-price').textContent = new Intl.NumberFormat(locale, { style: 'currency', currency }).format(amount); const checkoutButton = document.querySelector('#checkout'); checkoutButton.disabled = false; checkoutButton.addEventListener('click', () => startCheckout(id)); document.querySelector('#checkout-message').textContent = 'Secure checkout is ready.'; } catch (error) { app.querySelector('.product-detail-page').innerHTML = `<section class="empty-state"><h1>Product not found</h1><a class="button" href="#/browse">Back to catalog</a></section>`; } }
async function renderBrowse() { const locale = getLocale(); const params = new URLSearchParams(location.hash.split('?')[1] || ''); const query = params.get('q') || ''; const category = params.get('category') || ''; app.innerHTML = header(locale) + '<main id="catalog-root"></main>'; wireLocale(); await renderCatalog({ root: document.querySelector('#catalog-root'), locale, t, query, category, onNavigate: (path) => { location.hash = `#${path}`; } }); }
function renderAuthPage(mode) { app.innerHTML = header(getLocale()) + '<div id="auth-root"></div>'; wireLocale(); renderAuth(document.querySelector('#auth-root'), mode); }
async function renderLibraryPage() { app.innerHTML = header(getLocale()) + '<main id="library-root"></main>'; wireLocale(); await renderLibrary(document.querySelector('#library-root')); }
async function renderWatchPage(productId) { app.innerHTML = header(getLocale()) + '<main id="watch-root"></main>'; wireLocale(); try { await authApi.me(); renderWatch(document.querySelector('#watch-root'), productId); } catch (error) { if (error.status === 401) { location.hash = `#/login?return=/watch/${encodeURIComponent(productId)}`; return; } document.querySelector('#watch-root').innerHTML = '<section class="empty-state"><h2>Player unavailable</h2><p>Please try again shortly.</p></section>'; } }
async function renderSellerPage(section = 'overview') { app.innerHTML = header(getLocale()) + '<main id="seller-root"></main>'; wireLocale(); const root = document.querySelector('#seller-root'); try { await authApi.me(); if (section === 'register') return renderSellerApplication(root); if (section === 'products') return renderSellerProducts(root); if (section === 'upload') return renderSellerUpload(root); if (section === 'sales') return renderSellerEarnings(root); if (section === 'payouts') return renderSellerPayouts(root); if (section === 'profile' || section === 'verification') return renderSellerProfile(root); root.innerHTML = renderSellerDashboard(); } catch (error) { if (section === 'register' && error.status === 401) return renderSellerApplication(root); if (error.status === 401) { location.hash = `#/login?return=/seller/${encodeURIComponent(section)}`; return; } root.innerHTML = '<section class="empty-state"><h2>Seller dashboard unavailable</h2><p>Please try again shortly.</p></section>'; } }
async function renderAdminPage(section) { app.innerHTML = header(getLocale()) + '<main id="admin-root"></main>'; wireLocale(); const root = document.querySelector('#admin-root'); try { await authApi.me(); if (!section || section === 'overview') return root.innerHTML = renderAdminDashboard(); if (section === 'payouts') return renderAdminPayouts(root); if (section === 'seller-applications') return renderSellerApplications(root); if (section === 'verification' || section === 'verifications' || section === 'seller-verifications') return renderAdminVerifications(root); root.innerHTML = renderAdminDashboard(); } catch (error) { if (error.status === 401 || error.status === 403) { root.innerHTML = '<section class="empty-state"><h2>Admin access required</h2><p>Your account does not have permission to view this area.</p></section>'; return; } root.innerHTML = '<section class="empty-state"><h2>Admin dashboard unavailable</h2><p>Please try again shortly.</p></section>'; } }
async function renderCreatorsPage() { app.innerHTML = header(getLocale()) + '<main id="creators-root"></main>'; wireLocale(); renderCreators(document.querySelector('#creators-root')); }
function render() { const rawPath = location.hash.replace(/^#/, '').split('?')[0] || '/'; const productMatch = rawPath.match(/^\/product\/([^/]+)$/); const watchMatch = rawPath.match(/^\/watch\/([^/]+)$/); const sellerMatch = rawPath.match(/^\/seller(?:\/([^/]+))?$/); const adminMatch = rawPath.match(/^\/admin(?:\/([^/]+))?$/); if (productMatch) return renderProduct(decodeURIComponent(productMatch[1])); if (watchMatch) return renderWatchPage(decodeURIComponent(watchMatch[1])); if (sellerMatch) return renderSellerPage(sellerMatch[1] || 'overview'); if (adminMatch) return renderAdminPage(adminMatch[1]); if (rawPath === '/creators') return renderCreatorsPage(); if (rawPath === '/browse' || rawPath === '/categories' || rawPath === '/popular') return renderBrowse(); if (rawPath === '/library') return renderLibraryPage(); if (rawPath === '/login') return renderAuthPage('login'); if (rawPath === '/register') return renderAuthPage('register'); return renderHome(); }
window.addEventListener('hashchange', render); render();
