const $ = (s) => document.querySelector(s);
const currencyRates = { USD:1, EUR:.92, GBP:.78, JPY:156 };
const images = {
  Education:'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1000&q=85',
  Film:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1000&q=85',
  Business:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1000&q=85',
  Creative:'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1000&q=85',
  Adult:'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85'
};
let state = { role:'buyer', products:[], purchases:[], orders:[], sellerProducts:[], payouts:[], moderationQueue:[], sellerApplications:[] };
let activeTab = 'overview';
const money = (n) => new Intl.NumberFormat('ja-JP',{style:'currency',currency:$('#currency')?.value||'USD'}).format(n * (currencyRates[$('#currency')?.value||'USD']||1));
const esc = (v) => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path, options={}) { const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}}); const type=r.headers.get('content-type')||''; const data=type.includes('json')?await r.json():await r.blob(); if(!r.ok) throw new Error(data?.error||`HTTP ${r.status}`); return data; }
async function refresh(){ state=await api('/api/demo/state'); renderProducts(); renderCategories(); renderRole(); updateTop(); }
async function login(role){ const r=await api('/api/demo/login',{method:'POST',body:JSON.stringify({role})}); state=r.state||state; await refresh(); toast(`${role.toUpperCase()} mode activated`); }
function updateTop(){ const role=$('#role'), pill=$('#rolePill'); if(role) role.textContent=state.role.toUpperCase(); if(pill) pill.className=`pill ${state.role}`; }
function toast(msg){ const x=$('#toast'); if(!x)return; x.textContent=msg; x.classList.add('show'); clearTimeout(window.__toastTimer); window.__toastTimer=setTimeout(()=>x.classList.remove('show'),2200); }
function renderProducts(){ const host=$('#products'); if(!host)return; const q=($('#search')?.value||'').trim().toLowerCase(); const f=$('#filter')?.value||'All'; const list=state.products.filter(p=>(f==='All'||p.category===f)&&(!q||(p.title+' '+p.seller+' '+p.category).toLowerCase().includes(q))); host.innerHTML=list.map(p=>`<article class="card product"><div class="thumb"><img src="${images[p.category]||images.Education}" alt="${esc(p.title)}"><span class="badge">${esc(p.category)}${p.category==='Adult'?' · 18+':''}</span></div><div class="cardBody pbody"><h3>${esc(p.title)}</h3><p class="muted">by ${esc(p.seller)}</p><div class="rating">★ ${p.rating} <span>Verified creator</span></div><div class="foot prow"><b class="price">${money(p.price)}</b><button class="btn sm" onclick="openProduct(${p.id})">View details</button></div></div></article>`).join('') || '<div class="empty bigEmpty"><h3>No videos found</h3><p class="muted">Try another keyword or category.</p></div>'; }
function renderCategories(){ const host=$('#catgrid'); if(!host)return; const counts={}; state.products.forEach(p=>counts[p.category]=(counts[p.category]||0)+1); host.innerHTML=Object.keys(images).map(c=>`<button class="cat" onclick="selectCategory('${c}')"><img src="${images[c]}" alt="${c}"><b>${c}${c==='Adult'?' · 18+':''}</b><small>${counts[c]||0} video${counts[c]===1?'':'s'}</small></button>`).join(''); }
function selectCategory(category){ $('#filter').value=category; renderProducts(); goBrowse(); }
function openProduct(id){ const p=state.products.find(x=>x.id===id); if(!p)return; openModal(`<div class="detail"><img src="${images[p.category]||images.Education}" alt="${esc(p.title)}"><div><span class="eyebrow">${esc(p.category)}${p.category==='Adult'?' · 18+':''}</span><h2>${esc(p.title)}</h2><p class="muted">Premium video by <b>${esc(p.seller)}</b>. Purchase grants protected streaming and authorized download.</p><div class="facts"><span>★ ${p.rating}</span><span>${esc(p.meta)}</span><span>${money(p.price)}</span></div><button class="btn primary wide" onclick="purchase(${p.id})">Purchase securely · ${money(p.price)}</button><div class="secure">🔒 Demo checkout · order + entitlement are stored server-side</div></div></div>`); }
async function purchase(id){ const r=await api('/api/demo/purchase',{method:'POST',body:JSON.stringify({productId:id})}); state=r.state; closeModal(); renderRole(); updateTop(); toast(`Purchase ${r.order.id} completed`); }
function buyerView(){ const purchases=state.purchases.map(id=>state.products.find(p=>p.id===id)).filter(Boolean); return `<div class="dashboard"><div class="dashHead"><div><span class="eyebrow">Buyer workspace</span><h2>My Library</h2><p class="muted">Your paid purchases and protected media.</p></div><button class="btn" onclick="showOrders()">Order history (${state.orders.length})</button></div>${purchases.length?`<div class="cards libraryGrid">${purchases.map(p=>`<article class="card"><div class="thumb"><img src="${images[p.category]||images.Education}" alt="${esc(p.title)}"><span class="badge">Purchased</span></div><div class="cardBody"><h3>${esc(p.title)}</h3><p class="muted">Entitlement: <b class="ok">ACTIVE</b></p><div class="actions"><button class="btn primary" onclick="watch(${p.id})">▶ Watch</button><a class="btn" href="/api/demo/media/${p.id}?download=1">↓ Download</a></div></div></article>`).join('')}</div>`:`<div class="empty bigEmpty"><h3>Your library is empty</h3><p>Buy a video to unlock Watch + Download.</p><button class="btn primary" onclick="goMarketplace()">Explore videos</button></div>`}</div>`; }
function showOrders(){ $('#workspace').innerHTML=`<div class="dashboard"><div class="dashHead"><div><span class="eyebrow">Buyer workspace</span><h2>Order history</h2></div><button class="btn" onclick="renderRole()">← Library</button></div><div class="tableWrap"><table><tr><th>Order</th><th>Product</th><th>Status</th><th>Total</th></tr>${state.orders.map(o=>{const p=state.products.find(x=>x.id===o.productId);return `<tr><td>${esc(o.id)}</td><td>${esc(p?.title||'Video')}</td><td><span class="status">PAID</span></td><td>${money(o.total)}</td></tr>`}).join('')||'<tr><td colspan="4">No orders yet.</td></tr>'}</table></div></div>`; $('#workspace').scrollIntoView({behavior:'smooth'}); }
function watch(id){ openModal(`<div class="playerModal"><span class="eyebrow">Protected media</span><h2>Authorized playback</h2><video controls autoplay playsinline src="/api/demo/media/${id}"></video><div class="secure">🔐 Server entitlement checked before media delivery · private/no-store · range streaming</div></div>`); }
function sellerView(){ const own=state.sellerProducts; $('#workspace').innerHTML=`<div class="dashboard"><div class="dashHead"><div><span class="eyebrow">Creator workspace</span><h2>Creator Studio</h2><p class="muted">Create, publish, earn and request payouts.</p></div><button class="btn primary" onclick="newProduct()">＋ New product</button></div><div class="metrics"><div><b>$8,420</b><span>Available earnings</span></div><div><b>$1,180</b><span>Pending earnings</span></div><div><b>${own.length}</b><span>Your products</span></div><div><b>4.9</b><span>Creator rating</span></div></div><div class="split"><div class="panel"><h3>Your products</h3>${own.length?own.map(p=>`<div class="listRow"><div><b>${esc(p.title)}</b><small>${esc(p.category)} · ${money(p.price)}</small></div><span class="status">${p.mediaReady?'READY':'MEDIA NEEDED'}</span><button class="btn sm" onclick="uploadProduct('${esc(p.id)}')">${p.mediaReady?'Media ready':'Upload media'}</button></div>`).join(''):'<p class="muted">No products yet. Create your first product to enter moderation.</p>'}</div><div class="panel"><h3>Payouts</h3><p class="muted">Request a demo payout for operator review.</p><button class="btn primary" onclick="requestPayout()">Request payout</button>${state.payouts.map(p=>`<div class="listRow"><span>${esc(p.id)}</span><span>${money(p.amount)}</span><span class="status">${esc(p.status)}</span></div>`).join('')}</div></div></div>`; }
function newProduct(){ openModal(`<span class="eyebrow">Creator Studio</span><h2>Create product</h2><form onsubmit="createProduct(event)" class="form"><label>Title<input name="title" required maxlength="120" placeholder="Your video title"></label><label>Category<select name="category"><option>Education</option><option>Film</option><option>Business</option><option>Creative</option><option>Adult</option></select></label><label>Price<input name="price" type="number" min="1" max="9999" step="1" value="20" required></label><button class="btn primary" type="submit">Create product</button></form>`); }
async function createProduct(e){e.preventDefault();try{const f=new FormData(e.target);const r=await api('/api/demo/seller/product',{method:'POST',body:JSON.stringify({title:f.get('title'),category:f.get('category'),price:Number(f.get('price'))})});state=r.state;closeModal();sellerView();toast('Product created and sent to moderation');}catch(err){toast(err.message)}}
async function uploadProduct(id){try{const r=await api('/api/demo/seller/upload',{method:'POST',body:JSON.stringify({productId:id})});state=r.state;sellerView();openModal(`<span class="eyebrow">Media pipeline</span><h2>Upload accepted</h2><div class="pipeline">${r.lifecycle.map((x,i)=>`<div class="pipe"><b>${i+1}</b><span>${esc(x)}</span><strong class="ok">✓</strong></div>`).join('')}</div><p class="secure">Demo media validation and storage lifecycle completed.</p>`);}catch(err){toast(err.message)}}
async function requestPayout(){try{const r=await api('/api/demo/seller/payout',{method:'POST',body:JSON.stringify({amount:125})});state=r.state;sellerView();toast(`${r.payout.id} submitted for review`);}catch(err){toast(err.message)}}
function adminView(){const pending=state.moderationQueue.filter(x=>x.status==='pending');const sellers=state.sellerApplications.filter(x=>x.status==='pending');$('#workspace').innerHTML=`<div class="dashboard"><div class="dashHead"><div><span class="eyebrow">Operator console</span><h2>Administration</h2><p class="muted">Moderation, seller verification and payout oversight.</p></div></div><div class="metrics"><div><b>${state.products.length}</b><span>Catalog products</span></div><div><b>${pending.length}</b><span>Moderation queue</span></div><div><b>${sellers.length}</b><span>Seller applications</span></div><div><b>${state.payouts.length}</b><span>Demo payouts</span></div></div><div class="split"><div class="panel"><h3>Product moderation</h3>${pending.map(x=>`<div class="listRow"><div><b>${esc(x.title)}</b><small>${esc(x.seller)}</small></div><button class="btn sm" onclick="moderate('${esc(x.id)}','approve')">Approve</button><button class="btn sm danger" onclick="moderate('${esc(x.id)}','reject')">Reject</button></div>`).join('')||'<p class="muted">Queue clear.</p>'}</div><div class="panel"><h3>Seller verification</h3>${sellers.map(x=>`<div class="listRow"><div><b>${esc(x.seller)}</b><small>Application ${esc(x.id)}</small></div><button class="btn sm" onclick="sellerApproval('${esc(x.id)}','approve')">Approve</button><button class="btn sm danger" onclick="sellerApproval('${esc(x.id)}','reject')">Reject</button></div>`).join('')||'<p class="muted">Queue clear.</p>'}</div></div><div class="panel securityPanel"><h3>Security controls</h3><div class="securityGrid"><span>✓ Session authentication</span><span>✓ Role authorization</span><span>✓ Entitlement-protected media</span><span>✓ Range streaming</span><span>✓ Private/no-store media</span><span>✓ Upload lifecycle validation</span></div></div></div>`; }
async function moderate(id,action){try{const r=await api('/api/demo/admin/moderation',{method:'POST',body:JSON.stringify({id,action})});state=r.state;adminView();toast(`Moderation ${action}d`);}catch(err){toast(err.message)}}
async function sellerApproval(id,action){try{const r=await api('/api/demo/admin/seller-approval',{method:'POST',body:JSON.stringify({id,action})});state=r.state;adminView();toast(`Seller ${action}d`);}catch(err){toast(err.message)}}
function renderRole(){if(state.role==='buyer')$('#workspace').innerHTML=buyerView();else if(state.role==='seller')sellerView();else adminView();}
function hideWorkspace(){ $('#workspace')?.classList.remove('show'); }
function goMarketplace(){hideWorkspace();$('#market').scrollIntoView({behavior:'smooth'});}
function showModal(){ $('#modal').classList.add('show'); }
function closeModal(){ $('#modal').classList.remove('show'); }
function openModal(html){ $('#modal').innerHTML=`<div class="modal"><button class="x" onclick="closeModal()" aria-label="Close">×</button>${html}</div>`;showModal(); }
function goHome(){hideWorkspace();window.scrollTo({top:0,behavior:'smooth'});}
function goBrowse(){hideWorkspace();setTimeout(()=>$('#market').scrollIntoView({behavior:'smooth'}),20);}
function goCategories(){hideWorkspace();setTimeout(()=>$('#categorySection').scrollIntoView({behavior:'smooth'}),20);}
function showBuyer(){activeTab='library';login('buyer').then(()=>{renderRole();$('#workspace').scrollIntoView({behavior:'smooth'});}).catch(e=>toast(e.message));}
function showSeller(){activeTab='overview';login('seller').then(()=>sellerView()).catch(e=>toast(e.message));}
function showAdmin(){activeTab='overview';login('admin').then(()=>adminView()).catch(e=>toast(e.message));}
function loginModal(){openModal(`<span class="eyebrow">Demo access</span><h2>Choose a workspace</h2><p class="muted">No real credentials are required. This switches the server-backed demo session.</p><div class="actions"><button class="btn primary" onclick="closeModal();login('buyer')">Buyer</button><button class="btn" onclick="closeModal();showSeller()">Seller</button><button class="btn" onclick="closeModal();showAdmin()">Admin</button></div>`);}
window.openProduct=openProduct;window.purchase=purchase;window.watch=watch;window.login=login;window.sellerView=sellerView;window.adminView=adminView;window.buyerView=()=>{$('#workspace').innerHTML=buyerView()};window.newProduct=newProduct;window.createProduct=createProduct;window.uploadProduct=uploadProduct;window.requestPayout=requestPayout;window.moderate=moderate;window.sellerApproval=sellerApproval;window.showOrders=showOrders;window.closeModal=closeModal;window.openModal=openModal;window.goHome=goHome;window.goBrowse=goBrowse;window.goCategories=goCategories;window.showBuyer=showBuyer;window.showSeller=showSeller;window.showAdmin=showAdmin;window.loginModal=loginModal;window.goMarketplace=goMarketplace;window.selectCategory=selectCategory;
$('#search')?.addEventListener('input',renderProducts);$('#filter')?.addEventListener('change',renderProducts);$('#currency')?.addEventListener('change',renderProducts);$('#modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal();});
refresh().catch(e=>toast(e.message));
