(() => {
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(path,opt={})=>{const r=await fetch(path,{credentials:'same-origin',...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d};
const ps=()=>demoState?.products||[];const p=id=>ps().find(x=>x.id===Number(id));
async function sync(){demoState=await api('/api/demo/state');return demoState}
async function role(r){demoState=await api('/api/demo/login',{method:'POST',body:JSON.stringify({role:r})});closeModal();r==='buyer'?library():r==='seller'?seller('overview'):admin('overview')}
window.login=()=>openModal(`<div class="ey">DEMO LOGIN</div><h2>Choose a role</h2><p class="muted">No credentials are stored. Each role uses the same functional demo session.</p><div class="steps"><button class="step" onclick="demoRole('buyer')"><b>Buyer</b><span>Browse, purchase, library, watch, download</span></button><button class="step" onclick="demoRole('seller')"><b>Seller</b><span>Products, media, earnings, payouts, profile</span></button><button class="step" onclick="demoRole('admin')"><b>Admin</b><span>Moderation, seller verification, payouts, security</span></button></div>`);
window.demoRole=role;
window.product=i=>{const x=ps()[i]||products[i];if(!x)return;openModal(`<div class="detail"><div>${art(x.kind)}</div><div><div class="ey">${esc(x.category)}${x.category==='Adult'?' · 18+':''}</div><h2>${esc(x.title)}</h2><p class="muted">${esc(x.meta)} · ${esc(x.seller)}. Lifetime access with protected Watch and Download after purchase.</p><div class="steps"><div class="step done">✓ Preview before purchase</div><div class="step">🔒 Demo checkout</div><div class="step">✓ Entitlement after payment</div><div class="step">↓ Protected download</div></div><div class="price"><b>${money(x.price)}</b><button class="btn primary" onclick="demoPurchase(${x.id})">Buy now</button></div></div></div>`)};
window.demoPurchase=async id=>{try{const d=await api('/api/demo/purchase',{method:'POST',body:JSON.stringify({productId:id})});demoState=d.state;openModal(`<div class="ey">ORDER ${esc(d.order.id)}</div><h2>Purchase successful</h2><div class="steps"><div class="step done">✓ Payment authorized</div><div class="step done">✓ Order paid</div><div class="step done">✓ Entitlement granted</div><div class="step done">✓ Watch + Download enabled</div></div><button class="btn primary" onclick="closeModal();library()">Open My Library</button>`)}catch(e){openModal(`<h2>Purchase failed</h2><p>${esc(e.message)}</p>`)}};
window.library=async()=>{const s=await sync();showDash('Buyer area','My Library',[['library','Library','library()'],['orders','Orders','orders()'],['account','Account','account()']],s.purchases.length?`<div class="grid"><div class="dash-card"><strong>${s.purchases.length}</strong><p>Purchased videos</p><button class="btn primary" onclick="watch()">▶ Watch</button></div><div class="dash-card"><strong>${s.purchases.length}</strong><p>Downloads</p><button class="btn primary" onclick="downloadDemo()">↓ Download</button></div><div class="dash-card"><strong style="color:var(--ok)">Active</strong><p>Entitlement</p><span class="status">Protected access</span></div></div>`:`<div class="dash-card"><strong>0</strong><p>No purchases yet.</p><button class="btn primary" onclick="browse()">Discover videos</button></div>`)};
window.watch=async()=>{const s=await sync(),id=s.purchases[0],x=p(id);openModal(`<div class="ey">PROTECTED PLAYER</div><h2>${esc(x.title)}</h2><video class="video" controls autoplay src="/api/demo/media/${id}"></video><div class="step done" style="margin-top:10px">✓ Server entitlement verified</div>`)};
window.downloadDemo=async()=>{const s=await sync(),id=s.purchases[0],x=p(id);openModal(`<div class="ey">PROTECTED DOWNLOAD</div><h2>${esc(x.title)}</h2><p class="muted">The server will send the purchased demo asset with attachment disposition.</p><a class="btn primary" style="display:block;text-align:center;text-decoration:none" href="/api/demo/media/${id}?download=1">↓ Download demo video</a>`)};
window.orders=async()=>{const s=await sync();showDash('Buyer area','Orders',[['library','Library','library()'],['orders','Orders','orders()'],['account','Account','account()']],`<div class="dash-card"><table class="table"><tr><th>Order</th><th>Product</th><th>Status</th><th>Total</th></tr>${s.orders.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(p(o.productId)?.title||'')}</td><td><span class="status">${esc(o.status)}</span></td><td>${money(o.total)}</td></tr>`).join('')||'<tr><td colspan="4">No orders yet.</td></tr>'}</table></div>`)};
window.account=async()=>{const s=await sync();showDash('Buyer area','Account',[['library','Library','library()'],['orders','Orders','orders()'],['account','Account','account()']],`<div class="dash-card"><h3>${esc(s.account.email)}</h3><div class="steps"><div class="step done">✓ Verified demo account</div><div class="step done">✓ HTTP-only session cookie</div></div></div>`)};
window.seller=async tab=>{if(!demoState||demoState.role!=='seller')await role('seller');else await sync();dashTab=tab||dashTab||'overview';const nav=[['overview','Overview','seller(\'overview\')'],['products','Products','seller(\'products\')'],['upload','Upload','seller(\'upload\')'],['earnings','Earnings','seller(\'earnings\')'],['payouts','Payouts','seller(\'payouts\')'],['profile','Profile','seller(\'profile\')']];let c='';if(dashTab==='products')c=`<div class="dash-card"><table class="table"><tr><th>Product</th><th>Price</th><th>Media</th><th>Status</th></tr>${demoState.sellerProducts.map(x=>`<tr><td>${esc(x.title)}</td><td>${money(x.price)}</td><td>${x.mediaReady?'Ready':'Missing'}</td><td>${esc(x.status)}</td></tr>`).join('')||'<tr><td colspan="4">No seller products yet.</td></tr>'}</table></div>`;else if(dashTab==='upload')c=`<div class="dash-card"><h3>New video product</h3><div class="form"><input id="sp-title" placeholder="Product title"><select id="sp-cat"><option>Education</option><option>Film</option><option>Business</option><option>Creative</option><option>Adult</option></select><input id="sp-price" type="number" value="20"><button class="btn primary" onclick="demoCreateProduct()">Create + upload demo media</button></div></div>`;else if(dashTab==='earnings')c='<div class="grid"><div class="dash-card"><strong>$8,420</strong><p>Available</p></div><div class="dash-card"><strong>$1,180</strong><p>Pending</p></div><div class="dash-card"><strong>'+demoState.orders.length+'</strong><p>Purchases</p></div></div>';else if(dashTab==='payouts')c=`<div class="dash-card"><strong>$8,420</strong><p>Available balance</p><button class="btn primary" onclick="demoPayout()">Request payout</button><div class="steps">${demoState.payouts.map(x=>`<div class="step"><b>${esc(x.id)}</b><span>${money(x.amount)} · ${esc(x.status)}</span></div>`).join('')}</div></div>`;else if(dashTab==='profile')c='<div class="dash-card"><h3>Demo Creator</h3><div class="steps"><div class="step done">✓ Profile complete</div><div class="step done">✓ Identity verification approved</div><div class="step done">✓ Payment settings metadata</div></div></div>';else c='<div class="grid"><div class="dash-card"><strong>$8,420</strong><p>Available earnings</p></div><div class="dash-card"><strong>'+demoState.sellerProducts.length+'</strong><p>Products</p></div><div class="dash-card"><strong>4.9/5</strong><p>Rating</p></div></div><div class="notice">Real HTTP demo path: product → media lifecycle → publication → sales → earnings → payout.</div>';showDash('Creator Studio','Sell videos globally',nav,c)};
window.demoCreateProduct=async()=>{try{const d=await api('/api/demo/seller/product',{method:'POST',body:JSON.stringify({title:$("sp-title").value,category:$("sp-cat").value,price:$("sp-price").value})});demoState=d.state;await api('/api/demo/seller/upload',{method:'POST',body:JSON.stringify({productId:d.product.id})});await seller('products')}catch(e){openModal(`<h2>Product action failed</h2><p>${esc(e.message)}</p>`)}};
window.demoPayout=async()=>{try{const d=await api('/api/demo/seller/payout',{method:'POST',body:JSON.stringify({amount:1000})});demoState=d.state;openModal(`<h2>Payout requested</h2><div class="step done">✓ ${esc(d.payout.id)} moved to reviewing</div><button class="btn primary" onclick="closeModal();seller('payouts')">View payout</button>`)}catch(e){openModal(`<h2>Payout failed</h2><p>${esc(e.message)}</p>`)}};
window.admin=async tab=>{demoState=await api('/api/demo/login',{method:'POST',body:JSON.stringify({role:'admin'})});dashTab=tab||dashTab||'overview';const nav=[['overview','Overview','admin(\'overview\')'],['products','Moderation','admin(\'products\')'],['sellers','Seller verification','admin(\'sellers\')'],['payouts','Payouts','admin(\'payouts\')'],['security','Security','admin(\'security\')']];let c='';if(dashTab==='products')c=`<div class="dash-card"><table class="table"><tr><th>Item</th><th>Creator</th><th>Status</th><th></th></tr>${demoState.moderationQueue.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.seller)}</td><td>${esc(x.status)}</td><td>${x.status==='pending'?`<button class="btn primary" onclick="moderate('${x.id}')">Approve</button>`:'—'}</td></tr>`).join('')}</table></div>`;else if(dashTab==='sellers')c=`<div class="dash-card"><table class="table"><tr><th>Application</th><th>Creator</th><th>Status</th><th></th></tr>${demoState.sellerApplications.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.seller)}</td><td>${esc(x.status)}</td><td>${x.status==='pending'?`<button class="btn primary" onclick="approveSeller('${x.id}')">Approve</button>`:'—'}</td></tr>`).join('')}</table></div>`;else if(dashTab==='payouts')c='<div class="dash-card"><p class="muted">Payout requests created by the demo seller session are visible here after role switching.</p><table class="table"><tr><th>Payout</th><th>Amount</th><th>Status</th></tr>'+demoState.payouts.map(x=>`<tr><td>${esc(x.id)}</td><td>${money(x.amount)}</td><td>${esc(x.status)}</td></tr>`).join('')+'</table></div>';else if(dashTab==='security')c='<div class="grid"><div class="dash-card"><strong>✓</strong><p>Role checks</p></div><div class="dash-card"><strong>✓</strong><p>Protected media</p></div><div class="dash-card"><strong>✓</strong><p>No payment secrets</p></div></div>';else c='<div class="grid"><div class="dash-card"><strong>'+demoState.products.length+'</strong><p>Products</p></div><div class="dash-card"><strong>'+demoState.sellerApplications.length+'</strong><p>Seller applications</p></div><div class="dash-card"><strong>'+demoState.moderationQueue.length+'</strong><p>Moderation items</p></div></div><div class="notice">Admin actions are real state-changing HTTP requests inside the functional demo.</div>';showDash('Operator Console','Admin & moderation',nav,c)};
window.moderate=async id=>{demoState=(await api('/api/demo/admin/moderation',{method:'POST',body:JSON.stringify({id,action:'approve'})})).state;admin('products')};window.approveSeller=async id=>{demoState=(await api('/api/demo/admin/seller-approval',{method:'POST',body:JSON.stringify({id,action:'approve'})})).state;admin('sellers')};
sync().then(()=>console.log('VIDORA functional demo backend connected')).catch(console.error);
})();
