const base = `http://127.0.0.1:${process.env.PORT || 4173}`;
const assert = (ok, message) => { if (!ok) throw new Error(message); };
const cookie = jar => ({ headers: jar ? { cookie: jar } : {} });
let jar = '';
async function req(path, options = {}) {
  const headers = { ...(options.headers || {}), ...(jar ? { cookie: jar } : {}) };
  const r = await fetch(base + path, { ...options, headers });
  const set = r.headers.get('set-cookie');
  if (set) jar = set.split(';')[0];
  const type = r.headers.get('content-type') || '';
  return { r, data: type.includes('json') ? await r.json() : await r.arrayBuffer() };
}
const health = await req('/api/health');
assert(health.r.ok && health.data.status === 'ok', 'health failed');
let state = (await req('/api/demo/state')).data;
assert(state.role === 'buyer', 'default role failed');
const loginBuyer = await req('/api/demo/login', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({role:'buyer'}) });
assert(loginBuyer.r.ok, 'buyer login failed');
const purchase = await req('/api/demo/purchase', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({productId:1}) });
assert(purchase.r.status === 201 && purchase.data.order.entitlement === 'active', 'purchase failed');
const media = await req('/api/demo/media/1', { headers:{range:'bytes=0-15'} });
assert(media.r.status === 206 && media.r.headers.get('content-type') === 'video/webm', 'authorized media failed');
const unauthorizedJar = jar;
await req('/api/demo/login', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({role:'seller'}) });
const blocked = await req('/api/demo/media/1');
assert(blocked.r.status === 404, 'role/session media boundary failed');
const product = await req('/api/demo/seller/product', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({title:'E2E Demo Product',category:'Education',price:12}) });
assert(product.r.status === 201 && product.data.product.mediaReady === false, 'seller product failed');
const upload = await req('/api/demo/seller/upload', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({productId:product.data.product.id}) });
assert(upload.r.ok && upload.data.product.mediaReady === true && upload.data.lifecycle.at(-1) === 'ready', 'seller upload failed');
const payout = await req('/api/demo/seller/payout', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({amount:125}) });
assert(payout.r.status === 201 && payout.data.payout.status === 'reviewing', 'seller payout failed');
const admin = await req('/api/demo/login', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({role:'admin'}) });
assert(admin.r.ok, 'admin login failed');
const adminState = admin.data;
const mod = adminState.moderationQueue.find(x => x.title === 'E2E Demo Product');
assert(mod, 'moderation item missing');
const approve = await req('/api/demo/admin/moderation', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({id:mod.id,action:'approve'}) });
assert(approve.r.ok && approve.data.item.status === 'approved', 'moderation approve failed');
const seller = adminState.sellerApplications.find(x => x.id === 'SEL-1001');
const sellerApprove = await req('/api/demo/admin/seller-approval', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({id:seller.id,action:'approve'}) });
assert(sellerApprove.r.ok && sellerApprove.data.item.status === 'approved', 'seller approval failed');
console.log('FUNCTIONAL_DEMO_E2E_GREEN');
console.log('buyer purchase -> entitlement -> protected media: PASS');
console.log('seller product -> upload lifecycle -> payout: PASS');
console.log('admin moderation -> seller approval: PASS');
