import { readFile, writeFile, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';

const ROOT = fileURLToPath(new URL('.', import.meta.url));
const source = await readFile(join(ROOT, 'server.js'), 'utf8');
const marker = "  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); const s = session(req, res);";
const injected = `${marker}
  if (req.method === 'GET' && (url.pathname === '/ott-home.css' || url.pathname === '/ott-home-v2.css' || url.pathname === '/ott-home-v3.css' || url.pathname === '/ott-home-v4.css' || url.pathname === '/ott-home-v5.css' || url.pathname === '/ott-home-v6.css' || url.pathname === '/ott-home-v7.css' || url.pathname === '/ott-home-v8.css' || url.pathname === '/ott-home-v9.css' || url.pathname === '/ott-home-v10.css' || url.pathname === '/ott-home-v11.css' || url.pathname === '/ott-home-v12.css' || url.pathname === '/ott-home-v13.css' || url.pathname === '/ott-home-v14.css' || url.pathname === '/ott-home-v15.css')) {
    const cssMap = {'/ott-home-v15.css':'ott-home-v15.css','/ott-home-v14.css':'ott-home-v14.css','/ott-home-v13.css':'ott-home-v13.css','/ott-home-v12.css':'ott-home-v12.css','/ott-home-v11.css':'ott-home-v11.css','/ott-home-v10.css':'ott-home-v10.css','/ott-home-v9.css':'ott-home-v9.css','/ott-home-v8.css':'ott-home-v8.css','/ott-home-v7.css':'ott-home-v7.css','/ott-home-v6.css':'ott-home-v6.css','/ott-home-v5.css':'ott-home-v5.css','/ott-home-v4.css':'ott-home-v4.css','/ott-home-v3.css':'ott-home-v3.css','/ott-home-v2.css':'ott-home-v2.css','/ott-home.css':'ott-home.css'};
    const css = await readFile(join(ROOT, cssMap[url.pathname]), 'utf8');
    res.writeHead(200, {'content-type':'text/css; charset=utf-8','cache-control':'no-store'}); res.end(css); return;
  }
  if (req.method === 'GET' && (url.pathname === '/' || url.pathname === '/index.html')) {
    let html = await readFile(join(ROOT, 'index.html'), 'utf8');
    html = html.replace('/ott-home-v3.css?v=20260905-v3', '/ott-home-v15.css?v=20260905-v21');
    html = html.replace('<section class="trustbar">', '<section class="video-showcase"><div class="video-showcase-inner"><div class="video-showcase-head"><div><div class="video-showcase-kicker">CURATED VIDEO COLLECTION</div><h2>作品との出会いを、<br>もっと自由に。</h2></div><p class="video-showcase-copy">ひとつの作品だけではなく、いろんなクリエイターの映像を眺めながら、次に観たい一本を見つける。</p></div><div class="video-showcase-grid"><a class="showcase-card s1"><span class="showcase-index">01</span><div class="showcase-bg"></div><span class="showcase-label">THE LAST SIGNAL</span></a><a class="showcase-card s2"><span class="showcase-index">02</span><div class="showcase-bg"></div><span class="showcase-label">Tokyo After Hours</span></a><a class="showcase-card s3"><span class="showcase-index">03</span><div class="showcase-bg"></div><span class="showcase-label">Build Your Brand</span></a><a class="showcase-card s4"><span class="showcase-index">04</span><div class="showcase-bg"></div><span class="showcase-label">BLUE HORIZON</span></a><a class="showcase-card s5"><span class="showcase-index">05</span><div class="showcase-bg"></div><span class="showcase-label">Mastering Motion</span></a></div><div class="video-showcase-note"><span>DISCOVER / WATCH / PURCHASE</span><span>VIDORA</span></div></div></section><section class="trustbar">');
    html = html.replace('<a class="cat c5"><b>LIFESTYLE</b><span>ライフスタイル</span><i>→</i></a></div></section><section class="library"', '<a class="cat c5"><b>LIFESTYLE</b><span>ライフスタイル</span><i>→</i></a><a class="cat c6"><b>ADULT</b><span>アダルト</span><i>→</i></a></div></section><section class="library"');
    const collections = '<section class="video-collections"><div class="section-head"><div><span class="section-kicker">LATEST RELEASES</span><h2>新着動画</h2></div><a href="#videos">すべて見る <b>→</b></a></div><div class="collection-grid"><article class="collection-card"><div class="collection-thumb n1"></div><span>映像作品</span><h3>Frames of Tokyo</h3><p>by KEN FILMS</p><b>¥1,280</b></article><article class="collection-card"><div class="collection-thumb n2"></div><span>トラベル</span><h3>Across the Island</h3><p>by KOTO FILMS</p><b>¥980</b></article><article class="collection-card"><div class="collection-thumb n3"></div><span>ライフスタイル</span><h3>Slow Morning</h3><p>by YAMA FILM</p><b>¥780</b></article><article class="collection-card"><div class="collection-thumb n4"></div><span>音楽</span><h3>Live in Blue</h3><p>by ROOM 09</p><b>¥1,480</b></article><article class="collection-card"><div class="collection-thumb n5"></div><span>教育</span><h3>Designing Ideas</h3><p>by FRAME LAB</p><b>¥1,980</b></article><article class="collection-card"><div class="collection-thumb n6"></div><span>ビジネス</span><h3>Inside the Studio</h3><p>by MIKA</p><b>¥1,380</b></article></div></section><section class="genre-rail"><div class="section-head"><div><span class="section-kicker">EXPLORE BY MOOD</span><h2>気分から選ぶ</h2></div></div><div class="genre-track"><a class="genre-card g1"><div></div><strong>映画のような映像</strong><span>12,400作品</span></a><a class="genre-card g2"><div></div><strong>学びたい夜</strong><span>3,820作品</span></a><a class="genre-card g3"><div></div><strong>旅に出る</strong><span>5,160作品</span></a><a class="genre-card g4"><div></div><strong>音楽に浸る</strong><span>2,940作品</span></a><a class="genre-card g5"><div></div><strong>大人の映像</strong><span>18+ / 成人向け</span></a></div></section>';
    const recommendations = '<section class="genre-recommendations"><div class="section-head"><div><span class="section-kicker">EDITORIAL PICKS</span><h2>ジャンル別おすすめ</h2></div><a href="#videos">作品をもっと見る <b>→</b></a></div><div class="recommendation-grid"><article class="recommendation-card"><div class="recommendation-thumb r1"></div><div class="recommendation-meta"><span>シネマティック</span><h3>Night City Stories</h3><p>by NORTH LIGHTS</p></div></article><article class="recommendation-card"><div class="recommendation-thumb r2"></div><div class="recommendation-meta"><span>クリエイター</span><h3>Behind the Lens</h3><p>by KAI VISUALS</p></div></article><article class="recommendation-card"><div class="recommendation-thumb r3"></div><div class="recommendation-meta"><span>ビジネス</span><h3>Work, Ideas &amp; People</h3><p>by STUDIO COMMON</p></div></article><article class="recommendation-card"><div class="recommendation-thumb r4"></div><div class="recommendation-meta"><span>イベント</span><h3>One Night Live</h3><p>by ROOM 09</p></div></article><article class="recommendation-card"><div class="recommendation-thumb r5"></div><div class="recommendation-meta"><span>インタビュー</span><h3>Creators at Work</h3><p>by FRAME LAB</p></div></article><article class="recommendation-card"><div class="recommendation-thumb r6"></div><div class="recommendation-meta"><span>ラーニング</span><h3>Learn by Making</h3><p>by MAKER CLASS</p></div></article></div></section>';
    html = html.replace('<section class="platform">', collections + recommendations + '<section class="platform">');
    res.writeHead(200, {'content-type':'text/html; charset=utf-8','cache-control':'no-store'}); res.end(html); return;
  }
`;
if (!source.includes(marker)) throw new Error('server injection marker not found');
const patched = source.replace(marker, injected);
const temp = join(ROOT, `.server-${randomUUID()}.mjs`);
await writeFile(temp, patched, 'utf8');
try { await import(`file://${temp}`); } finally { try { await unlink(temp); } catch {} }
